name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Set Executable Permissions
        run: |
          chmod +x ./engines/stockfish

      - name: Run Bot
        run: |
            if (( $GITHUB_RUN_NUMBER % 2 == 1 )); then
            python -u user_interface.py
            else
            python -u user_interface.py --matchmaking
            fi
     
      - name: 🔁 Self-Restart (Fire-and-Forget)
        if: always()
        run: gh workflow run bot.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
